### ISSUE TITLE
wget script like for Alamofire example - wishlist

### ISSUE THREAD

**Issue by johndpope** [JohnSundell/Marathon-Examples#2]
I was digging through scripts and came across this  
https://github.com/mgrebenets/swift-scripts-sandbox

Do I need  https://github.com/CocoaPods/Rome ? to get Alamofire working with Marathon? or what do you suggest? 

Intention - I want to replace a wget script with Alamofire get request / destination

**Comment by johndpope** [comment]
marathon add https://github.com/Alamofire/Alamofire.git

<img width="721" alt="screen shot 2017-03-27 at 2 47 05 pm" src="https://cloud.githubusercontent.com/assets/289994/24372540/4fbd23be-12fc-11e7-938a-3ecb90084a5c.png">

rocking

**Comment by johndpope** [comment]
```
//
// Marathon sample usage:
// marathon run marathonRefreshJson.swift
// https://github.com/johnsundell/marathon
// 


// Usage from terminal 
// 1. install https://github.com/johnsundell/marathon
// 2. marathon add https://github.com/Alamofire/Alamofire.git
// 3. from terminal > marathon run marathonRefreshJson.swift

import Foundation


class Downloader {
    
    func fetchSaveURL(url:String,resource:String){
    // if I use ALamofire here - the requests don't go outbound - I added the necessary exceptions to plist - but no joy. 
        let process:Process = Process()
        process.launchPath = "/bin/bash"
        process.arguments = [
            "-c",
            "curl  \(url) > \(resource)"
        ]
        process.launch()
        process.waitUntilExit()
        
    }
    
    func fetchAndSaveAllFiles(){
        let plistUrl = URL(fileURLWithPath: "HTTPStub.plist")
        let plistContent = NSDictionary(contentsOf: plistUrl)!
        
        print(plistContent)
        if let urlArray = plistContent["StubbedUrls"]  as? [[String : AnyObject]]{
            for stub in urlArray{
                if let downloadUrl = stub["url"] as? String{
                    if let resource = stub["resource"] as? String{
                        fetchSaveURL(url:downloadUrl,resource:resource)
                        print("fetching:", downloadUrl)
                    }
                }
            }
        }
    }
}


let downloader = Downloader()
downloader.fetchAndSaveAllFiles()



```

**Comment by JohnSundell** [comment]
@johndpope Since Almofire does its work async, you need to use semaphores. I'd recommend reading @zntfdr's excellent article on how he built a web crawler Swift script, through the use of semaphores: https://medium.com/swiftly-swift/how-to-make-a-web-crawler-in-swift-3ed4977a181b.

**Comment by zntfdr** [comment]
@johndpope 
I don't use Alamofire but by looking at the code I guess you're downloading multiple files.

I like to use ``DispatchSemaphore`` to handle asynchronicity, but I'm sure there are other ways as well.

If you have a way to know when you've downloaded all your files, then you can pretty much do exactly as I did on the script cited above, otherwise it's a little bit trickier, my suggestion would be:

1. create a semaphore with a ``value`` as big as the files you'd like to download (``urlArray.count``?): 
``let semaphore = DispatchSemaphore(value: filesToDownloadCount)``

2.  call ``semaphore.wait()`` before each fetch: this way, when the main flow has requested to fetch all the files, the semaphore's value will be at zero;

3. at the very end of the file, make a cycle with as many ``wait`` calls as ``filesToDownloadCount``: this will stop the script from quitting as you're waiting for all the files to be downloaded;

4. at the end of each fetch callback call ``semaphore.signal()``;

Here's an example (you can just copy each part inside your code):

```
import UIKit

let filesToDownloadCount = 10
// point 1
let semaphore = DispatchSemaphore(value: filesToDownloadCount)

for i in 1...filesToDownloadCount {
  // point 2
  // calling wait (this is used only to decreased the semaphore value)
  print("wait")
  semaphore.wait()
  
  // I simulate the file fetch with a 1 second delay here
  DispatchQueue.global(qos: .background).asyncAfter(deadline: .now() + 1) {
    // this is the fetch callback
    // do what you must, at the end of the clousure put semaphore.signal()

    // point 4
    print("signal")
    semaphore.signal()
  }
}
// when we arrive here the semaphore value is zero

// point 3
// this cycle stops the main flow to quit, we will complete the whole cycle only after all the files have been downloaded
for i in 1...filesToDownloadCount {
  semaphore.wait()
}

print("now the script can finish")
```

Again, all of the above must be done only if you don't have any other way to know if you've completed all your fetches. Otherwise a simpler ``DispatchSemaphore`` with value 1 (like in the script linked by @JohnSundell ) will suffice.

I remain at your disposal for any further clarification 😃 

PS
You can run the code above in a (Xcode) Playground to see how it behaves.

PPS
Just in case you'd like to know more about ``DispatchSemaphore``, I'd like to let you know about [this other article](https://medium.com/swiftly-swift/a-quick-look-at-semaphores-6b7b85233ddb) that I've written a while ago 😄

**Comment by johndpope** [comment]
thanks @JohnSundell /  @zntfdr
I'll close this now - and reopen perhaps with a PR or gist when I get a chance to revisit this script with Alamofire. @zntfdr - I enjoyed your blog on queues. Certainly looks more favorable than the old lock / unlock crud that was necessary not so long ago. 

Definitely would be good for newbies picking up swift scripting to have a couple of pointers in the readme.

**Comment by zntfdr** [comment]
Yes this actually [got me](https://twitter.com/johnsundell/status/845936349094072320) as well a few days ago. 😅
I believe that it's up to @JohnSundell to decide whether an asynchronicity disclaimer on the README would be beneficial 😊
